version: 0.1

# environment_variables:
#   plaintext:
#     key: "value"
#     key: "value"
            
phases:
  pre_build:
    commands:
      - npm install
  # build:
  #   commands:
  #     - npm run build
artifacts:
  files:
    - handler.js
    - package.json
    - serverless.yml